mqtt:
  enabled: true
  host: mosquitto
  port: 1883

# Caméras - ESP32-CAM
cameras:
  parking_camera_178:
    enabled: true
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-http-mjpeg
      
      inputs:
        - path: http://10.246.52.178:8080
          input_args: -re          
          roles:
            - detect
            - record
    detect:
      width: 800
      height: 600
      fps: 4
      enabled: true
    objects:
      track:
        - car
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    snapshots:
      enabled: true
      retain:
        default: 7

  parking_camera_20:
    enabled: true
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-http-mjpeg
      
      inputs:
        - path: http://10.246.52.20:8080
          input_args: -re          
          roles:
            - detect
            - record
    detect:
      width: 800
      height: 600
      fps: 4
      enabled: true
    objects:
      track:
        - car
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    snapshots:
      enabled: true
      retain:
        default: 7